<script setup>
import { ref } from 'vue';

const steps = [
  { name: '文档上传', key: 'upload' },
  { name: 'IR提取', key: 'ir' },
  { name: '时序图', key: 'sequence' },
  { name: '安全属性', key: 'properties' },
  { name: 'ProVerif', key: 'proverif' },
];

const currentStep = ref(0);
const uploadedFile = ref(null);
const selectedProperties = ref([]);
const isParsing = ref(false);
const parsingProgress = ref(0);
const uploadHistory = ref([]);
const currentFileId = ref(null);

const securityProperties = [
  {
    id: 'confidentiality',
    name: '保密性',
    description: '确保协议中交换的信息不被未授权方获取',
    icon: 'M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z',
  },
  {
    id: 'authentication',
    name: '认证性',
    description: '确保通信双方的身份是真实可信的',
    icon: 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z',
  },
  {
    id: 'integrity',
    name: '完整性',
    description: '确保协议中传输的数据在传输过程中未被篡改',
    icon: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z',
  },
  {
    id: 'freshness',
    name: '新鲜性',
    description: '确保协议中使用的随机数和密钥是最新生成的',
    icon: 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z',
  },
  {
    id: 'agreement',
    name: '一致性',
    description: '确保通信双方对协议执行结果达成一致',
    icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
  },
  {
    id: 'forward_secrecy',
    name: '前向保密',
    description: '确保即使长期密钥泄露，过去的会话密钥也不会泄露',
    icon: 'M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z',
  },
];

const protocolIR = ref([]);

const proverifCode = ref('');

const handleFileUpload = async (e) => {
  const file = e.target.files[0];
  if (file) {
    // 重置所有状态
    resetAllStates();

    uploadedFile.value = file;
    isParsing.value = true;
    parsingProgress.value = 0;

    // 模拟文件解析过程
    await simulateFileParsing();

    // 解析完成后设置IR数据
    protocolIR.value = [
      {
        id: 'calculate_1',
        operator: 'A',
        desc: 'Generate a random number RA.',
      },
      {
        id: 'calculate_2',
        operator: 'A',
        desc: 'Calculate alpha^RA mod beta, where RA is the random number generated by A.',
      },
      {
        id: 'calculate_3',
        operator: 'A',
        desc: 'Encrypt alpha^RA mod beta using the shared password P to obtain P(alpha^RA mod beta).',
      },
      {
        id: 'message_1',
        sender: 'A',
        receiver: 'B',
        desc: 'A sends her name and P(alpha^RA mod beta) to B, initiating the protocol.',
      },
      { id: 'calculate_4', operator: 'B', desc: 'B picks a random number RB.' },
      {
        id: 'calculate_5',
        operator: 'B',
        desc: 'B uses the shared password P to decrypt P(alpha^RA mod beta).',
      },
      {
        id: 'calculate_6',
        operator: 'B',
        desc: 'B calculates (alpha^(RA*RB) mod beta) to derive the session key K.',
      },
      {
        id: 'calculate_7',
        operator: 'B',
        desc: 'B calculates (alpha^RB mod beta).',
      },
      {
        id: 'calculate_8',
        operator: 'B',
        desc: 'B encrypts (alpha^RB mod beta) using the shared password P to produce P(alpha^RB mod beta).',
      },
      {
        id: 'calculate_9',
        operator: 'B',
        desc: 'B encrypts challengeB with the session key K to produce K(challengeB).',
      },
      {
        id: 'message_2',
        sender: 'B',
        receiver: 'A',
        desc: 'B transmits P(alpha^RB mod beta) and K(challengeB) to A, allowing A to derive the session key and verify the challenge.',
      },
      {
        id: 'calculate_10',
        operator: 'A',
        desc: 'Decrypt P(alpha^RB mod beta) using the shared password P to obtain alpha^RB mod beta.',
      },
      {
        id: 'calculate_11',
        operator: 'A',
        desc: 'Calculate the session key K from alpha^(RA*RB) mod beta.',
      },
      {
        id: 'calculate_12',
        operator: 'A',
        desc: 'Decrypt K(challengeB) using the session key K to obtain challengeB.',
      },
      {
        id: 'calculate_13',
        operator: 'A',
        desc: 'Generate a random challenge challengeA.',
      },
      {
        id: 'calculate_14',
        operator: 'A',
        desc: 'Encrypt the concatenation of challengeA and challengeB using the session key K to obtain K(challengeA, challengeB).',
      },
      {
        id: 'message_3',
        sender: 'A',
        receiver: 'B',
        desc: 'A sends K(challengeA, challengeB) to B, enabling B to verify that A has correctly decrypted and responded to the challenge.',
      },
      {
        id: 'calculate_15',
        operator: 'B',
        desc: 'B decrypts K(challengeA, challengeB) using the session key K.',
      },
      {
        id: 'validate_1',
        operator: 'B',
        desc: 'B verifies that challengeB was echoed correctly in the decrypted message.',
      },
      {
        id: 'message_4',
        sender: 'B',
        receiver: 'A',
        desc: 'B sends K(challengeA) to A, allowing A to confirm that B has responded correctly, finalizing the key exchange process.',
      },
      {
        id: 'validate_2',
        operator: 'A',
        desc: 'Verify that the decrypted challengeA matches the original challengeA generated by A.',
      },
    ];

    // 添加到历史记录
    addToHistory(file);

    currentStep.value = 1;
    isParsing.value = false;
  }
};

const simulateFileParsing = () => {
  return new Promise((resolve) => {
    const interval = setInterval(() => {
      parsingProgress.value += Math.random() * 15;
      if (parsingProgress.value >= 100) {
        parsingProgress.value = 100;
        clearInterval(interval);
        setTimeout(resolve, 500);
      }
    }, 200);
  });
};

const addToHistory = (file) => {
  const record = {
    id: Date.now().toString(),
    fileName: file.name,
    fileSize: file.size,
    uploadTime: new Date().toLocaleString(),
    irData: [...protocolIR.value],
    selectedProperties: [...selectedProperties.value],
    proverifCode: proverifCode.value,
  };

  uploadHistory.value.unshift(record);
  currentFileId.value = record.id;

  // 限制历史记录数量
  if (uploadHistory.value.length > 5) {
    uploadHistory.value = uploadHistory.value.slice(0, 5);
  }
};

const loadHistoryRecord = (record) => {
  // 重置所有状态
  resetAllStates();

  uploadedFile.value = { name: record.fileName, size: record.fileSize };
  protocolIR.value = [...record.irData];
  selectedProperties.value = [...record.selectedProperties];
  proverifCode.value = record.proverifCode;
  currentFileId.value = record.id;
  currentStep.value = 1;
};

const deleteHistoryRecord = (id) => {
  const index = uploadHistory.value.findIndex((record) => record.id === id);
  if (index !== -1) {
    uploadHistory.value.splice(index, 1);
    if (currentFileId.value === id) {
      resetAllStates();
    }
  }
};

const resetAllStates = () => {
  protocolIR.value = [];
  selectedProperties.value = [];
  proverifCode.value = '';
  currentStep.value = 0;
  currentFileId.value = null;
};

const nextStep = () => {
  if (currentStep.value < 4) {
    currentStep.value++;
  }
};

const navigateToStep = (index) => {
  if (index <= currentStep.value || uploadedFile.value) {
    currentStep.value = index;
  }
};

const getOperationType = (id) => {
  if (id.includes('message')) return 'message';
  if (id.includes('validate')) return 'validate';
  return 'calculate';
};

const countByType = (type) => {
  return protocolIR.value.filter((step) => getOperationType(step.id) === type)
    .length;
};

const formatFileSize = (bytes) => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
};

const copyIR = () => {
  navigator.clipboard.writeText(JSON.stringify(protocolIR.value, null, 2));
  alert('IR数据已复制到剪贴板');
};

const copyCode = () => {
  navigator.clipboard.writeText(proverifCode.value);
  alert('ProVerif代码已复制到剪贴板');
};

const downloadCode = () => {
  const blob = new Blob([proverifCode.value], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'eke_v2_protocol.pv';
  a.click();
  URL.revokeObjectURL(url);
};

const toggleProperty = (propertyId) => {
  const index = selectedProperties.value.indexOf(propertyId);
  if (index === -1) {
    selectedProperties.value.push(propertyId);
  } else {
    selectedProperties.value.splice(index, 1);
  }
};

const removeProperty = (propertyId) => {
  const index = selectedProperties.value.indexOf(propertyId);
  if (index !== -1) {
    selectedProperties.value.splice(index, 1);
  }
};

const getPropertyName = (propertyId) => {
  const property = securityProperties.find((p) => p.id === propertyId);
  return property ? property.name : '';
};

const getPropertyDescription = (propertyId) => {
  const property = securityProperties.find((p) => p.id === propertyId);
  return property ? property.description : '';
};

const generateProVerifCode = () => {
  // 根据选择的安全属性生成不同的ProVerif代码
  let code = `(* EKE V2 Protocol - ProVerif Model *)\n\n`;

  // 基础类型和函数声明
  code += `(* Type declarations *)\ntype key.\ntype nonce.\ntype exponent.\n\n`;
  code += `(* Cryptographic primitives *)\nfun exp(exponent, exponent): exponent.\nfun senc(bitstring, key): bitstring.\nfun sdec(bitstring, key): bitstring.\n\n`;
  code += `equation forall m: bitstring, k: key; sdec(senc(m, k), k) = m.\n\n`;

  // 根据选择的安全属性添加相应的查询
  code += `(* Security queries *)\n`;

  if (selectedProperties.value.includes('confidentiality')) {
    code += `(* Confidentiality queries *)\n`;
    code += `query attacker(sessionKey).\n`;
    code += `query attacker(challengeA).\n`;
    code += `query attacker(challengeB).\n\n`;
  }

  if (selectedProperties.value.includes('authentication')) {
    code += `(* Authentication queries *)\n`;
    code += `query A:host, B:host; event(acceptA(B)) ==> event(startA(B)).\n`;
    code += `query B:host, A:host; event(acceptB(A)) ==> event(startB(A)).\n\n`;
  }

  if (selectedProperties.value.includes('integrity')) {
    code += `(* Integrity queries *)\n`;
    code += `query integrity: message1.\n`;
    code += `query integrity: message2.\n`;
    code += `query integrity: message3.\n`;
    code += `query integrity: message4.\n\n`;
  }

  if (selectedProperties.value.includes('freshness')) {
    code += `(* Freshness queries *)\n`;
    code += `query fresh: RA.\n`;
    code += `query fresh: RB.\n`;
    code += `query fresh: challengeA.\n`;
    code += `query fresh: challengeB.\n\n`;
  }

  if (selectedProperties.value.includes('agreement')) {
    code += `(* Agreement queries *)\n`;
    code += `query A:host, B:host; event(endA(B)) ==> event(beginB(A)).\n`;
    code += `query B:host, A:host; event(endB(A)) ==> event(beginA(B)).\n\n`;
  }

  if (selectedProperties.value.includes('forward_secrecy')) {
    code += `(* Forward secrecy queries *)\n`;
    code += `query attacker(sessionKey) ==> attacker(password).\n\n`;
  }

  // 常量定义
  code += `(* Constants *)\nconst alpha: exponent.\nconst beta: exponent.\nfree c: channel.\n\n`;

  // 会话密钥派生
  code += `(* Session key derivation *)\nfun derive_key(exponent): key.\n\n`;

  // 进程定义
  code += `(* Process for party A *)\nlet processA(P: key) =\n  new RA: exponent;\n  let gRA = exp(alpha, RA) in\n  let encGRA = senc(gRA, P) in\n  out(c, (encGRA));\n\n  in(c, (encGRB: bitstring, encChallengeB: bitstring));\n  let gRB = sdec(encGRB, P) in\n  let K = derive_key(exp(gRB, RA)) in\n  let challengeB = sdec(encChallengeB, K) in\n\n  new challengeA: nonce;\n  let response1 = senc((challengeA, challengeB), K) in\n  out(c, response1);\n\n  in(c, response2: bitstring);\n  let challengeA_verify = sdec(response2, K) in\n  0.\n\n`;

  code += `(* Process for party B *)\nlet processB(P: key) =\n  in(c, encGRA: bitstring);\n  let gRA = sdec(encGRA, P) in\n\n  new RB: exponent;\n  let gRB = exp(alpha, RB) in\n  let K = derive_key(exp(gRA, RB)) in\n\n  new challengeB: nonce;\n  let encGRB = senc(gRB, P) in\n  let encChallengeB = senc(challengeB, K) in\n  out(c, (encGRB, encChallengeB));\n\n  in(c, response1: bitstring);\n  let (challengeA: nonce, challengeB_verify: nonce) = sdec(response1, K) in\n\n  let response2 = senc(challengeA, K) in\n  out(c, response2);\n  0.\n\n`;

  // 主进程
  code += `(* Main process *)\nprocess\n  new P: key;\n  (processA(P) | processB(P))`;

  proverifCode.value = code;
  currentStep.value = 4;
};
</script>

<template>
  <div class="protocol-verification">
    <!-- Header -->
    <header class="header">
      <div class="header-content">
        <h1 class="title">Protocol Formal Verification System</h1>
        <p class="subtitle">基于中间表示的协议形式化验证平台</p>
      </div>
    </header>

    <!-- Main Layout -->
    <div class="main-layout">
      <!-- Top Navigation -->
      <nav class="top-nav">
        <div
          v-for="(step, index) in steps"
          :key="index"
          class="nav-item"
          :class="[
            { active: currentStep === index, completed: currentStep > index },
          ]"
          @click="navigateToStep(index)"
        >
          <span class="step-number">{{ index + 1 }}</span>
          <span class="step-name">{{ step.name }}</span>
        </div>
      </nav>

      <!-- Content Area -->
      <main class="content-area">
        <!-- Step 1: Upload -->
        <section v-show="currentStep === 0" class="section">
          <h2 class="section-title">文档上传</h2>
          <div class="section-content">
            <div class="upload-history" v-if="uploadHistory.length > 0">
              <h3>历史记录</h3>
              <div class="history-list">
                <div
                  v-for="(record, index) in uploadHistory"
                  :key="index"
                  class="history-item"
                  :class="[{ active: record.id === currentFileId }]"
                  @click="loadHistoryRecord(record)"
                >
                  <div class="file-name">{{ record.fileName }}</div>
                  <div class="file-info">
                    <span class="file-size">{{
                      formatFileSize(record.fileSize)
                    }}</span>
                    <span class="upload-time">{{ record.uploadTime }}</span>
                  </div>
                  <button
                    @click.stop="deleteHistoryRecord(record.id)"
                    class="delete-btn"
                  >
                    ×
                  </button>
                </div>
              </div>
            </div>

            <p class="description">
              请上传RFC格式的协议规范文档。系统将自动解析文档内容，提取协议的关键信息和交互流程。
            </p>
            <div class="upload-area">
              <input
                type="file"
                id="file-input"
                class="file-input"
                @change="handleFileUpload"
                accept=".pdf,.doc,.docx,.txt"
                :disabled="isParsing"
              />
              <label
                for="file-input"
                class="upload-label"
                :class="{ disabled: isParsing }"
              >
                <svg
                  width="48"
                  height="48"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                  />
                </svg>
                <span v-if="!isParsing">点击选择文件或拖拽到此处</span>
                <span v-else>正在解析文件，请稍候...</span>
                <span class="file-hint">支持 PDF, DOC, DOCX, TXT 格式</span>
              </label>
            </div>
            <div v-if="uploadedFile && !isParsing" class="file-info">
              <p><strong>已选择：</strong>{{ uploadedFile.name }}</p>
              <p>
                <strong>大小：</strong>{{ formatFileSize(uploadedFile.size) }}
              </p>
            </div>
            <div v-if="isParsing" class="parsing-progress">
              <div class="progress-bar">
                <div
                  class="progress-fill"
                  :style="{ width: `${parsingProgress}%` }"
                ></div>
              </div>
              <p class="progress-text">
                正在解析文档... {{ parsingProgress }}%
              </p>
            </div>
          </div>
        </section>

        <!-- Step 2: IR Display -->
        <section v-show="currentStep === 1" class="section">
          <h2 class="section-title">中间表示 (Intermediate Representation)</h2>
          <div class="section-content">
            <p class="description">
              以下是从协议文档中提取的中间表示语言(IR)。每个操作包含唯一标识符、操作者和详细描述。
            </p>

            <div class="ir-stats">
              <div class="stat-item">
                <span class="stat-label">总操作数</span>
                <span class="stat-value">{{ protocolIR.length }}</span>
              </div>
              <div class="stat-item">
                <span class="stat-label">消息传递</span>
                <span class="stat-value">{{ countByType('message') }}</span>
              </div>
              <div class="stat-item">
                <span class="stat-label">计算操作</span>
                <span class="stat-value">{{ countByType('calculate') }}</span>
              </div>
              <div class="stat-item">
                <span class="stat-label">验证操作</span>
                <span class="stat-value">{{ countByType('validate') }}</span>
              </div>
            </div>

            <div class="ir-display">
              <div class="ir-header">
                <h3>IR 数据结构</h3>
                <button @click="copyIR" class="btn-secondary">复制JSON</button>
              </div>
              <pre class="code-block">{{
                JSON.stringify(protocolIR, null, 2)
              }}</pre>
            </div>

            <button @click="nextStep" class="btn-primary">
              继续：生成时序图
            </button>
          </div>
        </section>

        <!-- Step 3: Sequence Diagram -->
        <section v-show="currentStep === 2" class="section">
          <h2 class="section-title">协议时序图</h2>
          <div class="section-content">
            <p class="description">
              可视化展示协议双方的交互过程，包括消息传递、计算和验证步骤。
            </p>

            <div class="legend">
              <div class="legend-item">
                <span class="legend-color message"></span>
                <span>消息传递</span>
              </div>
              <div class="legend-item">
                <span class="legend-color calculate"></span>
                <span>计算操作</span>
              </div>
              <div class="legend-item">
                <span class="legend-color validate"></span>
                <span>验证操作</span>
              </div>
            </div>

            <div class="sequence-diagram">
              <div class="sequence-grid">
                <!-- 参与方 A -->
                <div class="participant-column participant-a">
                  <div class="participant-header">
                    <div class="participant-label">参与方 A</div>
                  </div>
                  <div class="lifeline"></div>
                  <div class="operations">
                    <div
                      v-for="(step, index) in protocolIR"
                      :key="step.id"
                      class="operation-slot"
                    >
                      <div
                        v-if="step.operator === 'A' || step.sender === 'A'"
                        class="operation-item"
                        :class="[getOperationType(step.id)]"
                      >
                        <div class="step-info">
                          <strong>{{ step.id }}</strong
                          >: {{ step.desc }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- 消息传递列 -->
                <div class="message-column">
                  <div class="message-header">消息传递</div>
                  <div class="messages">
                    <div
                      v-for="(step, index) in protocolIR"
                      :key="step.id"
                      class="message-slot"
                    >
                      <div
                        v-if="getOperationType(step.id) === 'message'"
                        class="message-item"
                      >
                        <div class="message-direction">
                          <svg
                            v-if="step.sender === 'A'"
                            width="100"
                            height="30"
                            class="arrow-right"
                          >
                            <line
                              x1="0"
                              y1="15"
                              x2="90"
                              y2="15"
                              stroke="#2563eb"
                              stroke-width="2"
                            />
                            <polygon
                              points="90,10 100,15 90,20"
                              fill="#2563eb"
                            />
                          </svg>
                          <svg
                            v-else-if="step.sender === 'B'"
                            width="100"
                            height="30"
                            class="arrow-left"
                          >
                            <line
                              x1="10"
                              y1="15"
                              x2="100"
                              y2="15"
                              stroke="#2563eb"
                              stroke-width="2"
                            />
                            <polygon points="10,10 0,15 10,20" fill="#2563eb" />
                          </svg>
                        </div>
                        <div class="message-content">
                          <strong>{{ step.id }}</strong
                          >: {{ step.desc }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- 参与方 B -->
                <div class="participant-column participant-b">
                  <div class="participant-header">
                    <div class="participant-label">参与方 B</div>
                  </div>
                  <div class="lifeline"></div>
                  <div class="operations">
                    <div
                      v-for="(step, index) in protocolIR"
                      :key="step.id"
                      class="operation-slot"
                    >
                      <div
                        v-if="step.operator === 'B' || step.sender === 'B'"
                        class="operation-item"
                        :class="[getOperationType(step.id)]"
                      >
                        <div class="step-info">
                          <strong>{{ step.id }}</strong
                          >: {{ step.desc }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <button @click="nextStep" class="btn-primary">
              继续：选择安全属性
            </button>
          </div>
        </section>

        <!-- Step 4: Security Properties -->
        <section v-show="currentStep === 3" class="section">
          <h2 class="section-title">选择安全属性</h2>
          <div class="section-content">
            <p class="description">
              请选择您希望验证的安全属性。系统将根据您的选择生成相应的ProVerif形式化模型。
            </p>

            <div class="security-properties">
              <div class="properties-grid">
                <div
                  v-for="property in securityProperties"
                  :key="property.id"
                  class="property-card"
                  :class="[
                    { selected: selectedProperties.includes(property.id) },
                  ]"
                  @click="toggleProperty(property.id)"
                >
                  <div class="property-icon">
                    <svg
                      width="24"
                      height="24"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        :d="property.icon"
                      />
                    </svg>
                  </div>
                  <h3 class="property-title">{{ property.name }}</h3>
                  <p class="property-description">{{ property.description }}</p>
                </div>
              </div>
            </div>

            <div
              class="selected-properties"
              v-if="selectedProperties.length > 0"
            >
              <h3>已选择的安全属性</h3>
              <div class="selected-list">
                <span
                  v-for="propertyId in selectedProperties"
                  :key="propertyId"
                  class="selected-tag"
                >
                  {{ getPropertyName(propertyId) }}
                  <button
                    @click="removeProperty(propertyId)"
                    class="remove-btn"
                  >
                    ×
                  </button>
                </span>
              </div>
            </div>

            <button
              @click="generateProVerifCode"
              class="btn-primary"
              :disabled="selectedProperties.length === 0"
            >
              生成ProVerif代码
            </button>
          </div>
        </section>

        <!-- Step 5: ProVerif Code -->
        <section v-show="currentStep === 4" class="section">
          <h2 class="section-title">ProVerif 形式化模型</h2>
          <div class="section-content">
            <p class="description">
              基于中间表示和您选择的安全属性自动生成的ProVerif形式化验证代码。可用于验证协议的安全属性。
            </p>

            <div class="verification-info">
              <h3>验证说明</h3>
              <ul>
                <li v-for="property in selectedProperties" :key="property">
                  {{ getPropertyDescription(property) }}
                </li>
              </ul>
            </div>

            <div class="code-actions">
              <button @click="downloadCode" class="btn-secondary">
                下载代码
              </button>
              <button @click="copyCode" class="btn-secondary">复制代码</button>
            </div>

            <div class="code-container">
              <pre class="code-block proverif">{{ proverifCode }}</pre>
            </div>
          </div>
        </section>
      </main>
    </div>
  </div>
</template>

<style scoped>
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

.protocol-verification {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
  color: #333;
  background: #f8f9fa;
}

.header {
  background: #fff;
  border-bottom: 1px solid #dee2e6;
  box-shadow: 0 2px 4px rgb(0 0 0 / 5%);
}

.header-content {
  padding: 1.5rem 2rem;
}

.title {
  margin: 0 0 0.5rem;
  font-size: 1.75rem;
  font-weight: 600;
  color: #1a1a1a;
}

.subtitle {
  margin: 0;
  font-size: 0.95rem;
  color: #6c757d;
}

.main-layout {
  display: flex;
  flex: 1;
  flex-direction: column;
  overflow: hidden;
}

.top-nav {
  display: flex;
  padding: 0 1rem;
  overflow-x: auto;
  background: #fff;
  border-bottom: 1px solid #dee2e6;
}

.nav-item {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  padding: 1rem 1.5rem;
  white-space: nowrap;
  cursor: pointer;
  border-bottom: 3px solid transparent;
  transition: all 0.2s;
}

.nav-item:hover {
  background: #f8f9fa;
}

.nav-item.active {
  font-weight: 500;
  color: #0d6efd;
  background: #e7f3ff;
  border-bottom-color: #0d6efd;
}

.nav-item.completed {
  color: #198754;
}

.step-number {
  display: inline-flex;
  flex-shrink: 0;
  align-items: center;
  justify-content: center;
  width: 26px;
  height: 26px;
  margin-right: 0.75rem;
  font-size: 0.875rem;
  font-weight: 600;
  background: #e9ecef;
  border-radius: 50%;
}

.nav-item.active .step-number {
  color: #fff;
  background: #0d6efd;
}

.nav-item.completed .step-number {
  color: #fff;
  background: #198754;
}

.step-name {
  font-size: 0.9rem;
}

.content-area {
  flex: 1;
  overflow-y: auto;
  background: #fff;
}

.section {
  padding: 2rem;
}

.section-title {
  padding-bottom: 0.75rem;
  margin: 0 0 1.5rem;
  font-size: 1.5rem;
  font-weight: 600;
  color: #212529;
  border-bottom: 3px solid #0d6efd;
}

.section-content {
  margin-top: 1.5rem;
}

.description {
  margin-bottom: 1.5rem;
  font-size: 1rem;
  line-height: 1.7;
  color: #6c757d;
}

.upload-history {
  padding: 1.5rem;
  margin-bottom: 2rem;
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.upload-history h3 {
  margin: 0 0 1rem;
  font-size: 1.1rem;
  font-weight: 600;
  color: #212529;
}

.history-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.history-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem;
  cursor: pointer;
  background: #fff;
  border: 2px solid #e9ecef;
  border-radius: 6px;
  transition: all 0.3s;
}

.history-item:hover {
  background: #e7f3ff;
  border-color: #0d6efd;
}

.history-item.active {
  background: #e7f3ff;
  border-color: #0d6efd;
}

.file-name {
  flex: 1;
  font-weight: 500;
  color: #212529;
}

.file-info {
  display: flex;
  gap: 1rem;
  margin-right: 1rem;
  font-size: 0.875rem;
  color: #6c757d;
}

.delete-btn {
  padding: 0.25rem;
  font-size: 1.5rem;
  line-height: 1;
  color: #dc3545;
  cursor: pointer;
  background: none;
  border: none;
  border-radius: 4px;
}

.delete-btn:hover {
  background: #f8d7da;
}

.upload-area {
  margin: 2rem 0;
}

.file-input {
  display: none;
}

.upload-label {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 4rem 2rem;
  color: #6c757d;
  cursor: pointer;
  background: #f8f9fa;
  border: 2px dashed #adb5bd;
  border-radius: 8px;
  transition: all 0.3s;
}

.upload-label:hover:not(.disabled) {
  color: #0d6efd;
  background: #e7f3ff;
  border-color: #0d6efd;
}

.upload-label.disabled {
  cursor: not-allowed;
  opacity: 0.6;
}

.upload-label svg {
  margin-bottom: 1rem;
}

.file-hint {
  margin-top: 0.75rem;
  font-size: 0.875rem;
  color: #adb5bd;
}

.file-info-card {
  padding: 1.25rem;
  margin-top: 1.5rem;
  background: #d1e7dd;
  border-left: 4px solid #198754;
  border-radius: 6px;
}

.file-info p {
  margin-bottom: 0.5rem;
}

.file-info p:last-child {
  margin-bottom: 0;
}

.parsing-progress {
  margin-top: 1.5rem;
}

.progress-bar {
  width: 100%;
  height: 8px;
  overflow: hidden;
  background: #e9ecef;
  border-radius: 4px;
}

.progress-fill {
  height: 100%;
  background: #0d6efd;
  transition: width 0.3s ease;
}

.progress-text {
  margin-top: 0.5rem;
  font-size: 0.9rem;
  color: #6c757d;
  text-align: center;
}

.ir-stats {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin: 2rem 0;
}

.stat-item {
  padding: 1.5rem;
  text-align: center;
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.stat-label {
  display: block;
  margin-bottom: 0.75rem;
  font-size: 0.875rem;
  font-weight: 500;
  color: #6c757d;
}

.stat-value {
  display: block;
  font-size: 2.25rem;
  font-weight: 600;
  color: #0d6efd;
}

.ir-display {
  margin: 2rem 0;
  overflow: hidden;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.ir-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 1.5rem;
  background: #f8f9fa;
  border-bottom: 1px solid #dee2e6;
}

.ir-header h3 {
  margin: 0;
  font-size: 1rem;
  font-weight: 600;
}

.code-block {
  max-height: 500px;
  padding: 1.5rem;
  margin: 0;
  overflow: auto;
  font-family: Monaco, Menlo, 'Courier New', monospace;
  font-size: 0.875rem;
  line-height: 1.6;
  color: #212529;
  background: #f8f9fa;
}

.code-block.proverif {
  color: #06c;
}

.btn-primary,
.btn-secondary {
  padding: 0.75rem 1.5rem;
  font-size: 0.95rem;
  font-weight: 500;
  cursor: pointer;
  border: none;
  border-radius: 6px;
  transition: all 0.2s;
}

.btn-primary {
  color: #fff;
  background: #0d6efd;
}

.btn-primary:hover {
  background: #0b5ed7;
}

.btn-primary:disabled {
  cursor: not-allowed;
  background: #6c757d;
}

.btn-secondary {
  color: #0d6efd;
  background: #fff;
  border: 1px solid #0d6efd;
}

.btn-secondary:hover {
  background: #e7f3ff;
}

.legend {
  display: flex;
  gap: 2rem;
  padding: 1.25rem;
  margin: 1.5rem 0;
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.legend-item {
  display: flex;
  gap: 0.75rem;
  align-items: center;
  font-size: 0.9rem;
}

.legend-color {
  width: 24px;
  height: 24px;
  border: 1px solid rgb(0 0 0 / 10%);
  border-radius: 4px;
}

.legend-color.message {
  background: #0d6efd;
}

.legend-color.calculate {
  background: #6f42c1;
}

.legend-color.validate {
  background: #198754;
}

.sequence-diagram {
  position: relative;
  padding: 2.5rem;
  margin: 2rem 0;
  background: #fff;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.sequence-grid {
  display: grid;
  grid-template-columns: 2fr 1fr 2fr;
  gap: 1rem;
  align-items: start;
}

.participant-column {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.participant-header {
  margin-bottom: 1rem;
}

.participant-label {
  display: inline-block;
  padding: 1rem 2rem;
  font-weight: 600;
  color: #0d6efd;
  text-align: center;
  background: #fff;
  border: 2px solid #0d6efd;
  border-radius: 6px;
}

.lifeline {
  flex: 1;
  width: 2px;
  height: 100%;
  min-height: 60px;
  margin: 0 auto;
  background: #adb5bd;
}

.operations {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  width: 100%;
}

.operation-slot {
  display: flex;
  align-items: center;
  min-height: 80px;
}

.operation-item {
  width: 100%;
  padding: 1rem;
  font-size: 0.9rem;
  line-height: 1.6;
  border-left: 4px solid;
  border-radius: 6px;
}

.operation-item.calculate {
  background: #f3e5f5;
  border-left-color: #6f42c1;
}

.operation-item.validate {
  background: #d1e7dd;
  border-left-color: #198754;
}

.message-column {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.message-header {
  padding: 0.75rem 1.5rem;
  margin-bottom: 1rem;
  font-weight: 600;
  color: #0d6efd;
  text-align: center;
  background: #e7f3ff;
  border: 1px solid #0d6efd;
  border-radius: 6px;
}

.messages {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  width: 100%;
}

.message-slot {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 80px;
}

.message-item {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  align-items: center;
}

.message-direction {
  display: flex;
  justify-content: center;
}

.message-content {
  max-width: 300px;
  padding: 1rem;
  font-size: 0.9rem;
  line-height: 1.6;
  text-align: center;
  background: #e7f3ff;
  border-left: 4px solid #0d6efd;
  border-radius: 6px;
}

.arrow-right,
.arrow-left {
  display: block;
}

.security-properties {
  margin: 2rem 0;
}

.properties-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 1.5rem;
}

.property-card {
  padding: 1.5rem;
  cursor: pointer;
  background: #fff;
  border: 2px solid #e9ecef;
  border-radius: 8px;
  transition: all 0.3s;
}

.property-card:hover {
  border-color: #0d6efd;
  box-shadow: 0 4px 8px rgb(0 0 0 / 10%);
  transform: translateY(-2px);
}

.property-card.selected {
  background: #e7f3ff;
  border-color: #0d6efd;
}

.property-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  margin-bottom: 1rem;
  color: #0d6efd;
  background: #f8f9fa;
  border-radius: 8px;
}

.property-title {
  margin-bottom: 0.75rem;
  font-size: 1.1rem;
  font-weight: 600;
  color: #212529;
}

.property-description {
  font-size: 0.9rem;
  line-height: 1.6;
  color: #6c757d;
}

.selected-properties {
  padding: 1.5rem;
  margin: 2rem 0;
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.selected-properties h3 {
  margin: 0 0 1rem;
  font-size: 1.1rem;
  font-weight: 600;
}

.selected-list {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.selected-tag {
  display: flex;
  align-items: center;
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
  font-weight: 500;
  color: #fff;
  background: #0d6efd;
  border-radius: 20px;
}

.remove-btn {
  margin-left: 0.5rem;
  font-size: 1.2rem;
  line-height: 1;
  color: #fff;
  cursor: pointer;
  background: none;
  border: none;
}

.code-actions {
  display: flex;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.code-container {
  margin-bottom: 2rem;
  overflow: hidden;
  border: 1px solid #dee2e6;
  border-radius: 8px;
}

.verification-info {
  padding: 1.5rem;
  margin-bottom: 1.5rem;
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-left: 4px solid #0d6efd;
  border-radius: 8px;
}

.verification-info h3 {
  margin: 0 0 1rem;
  font-size: 1.1rem;
  font-weight: 600;
}

.verification-info ul {
  padding-left: 1.5rem;
  margin: 0;
}

.verification-info li {
  margin-bottom: 0.75rem;
  line-height: 1.7;
}

@media (max-width: 1024px) {
  .ir-stats {
    grid-template-columns: repeat(2, 1fr);
  }

  .properties-grid {
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  }

  .sequence-grid {
    grid-template-columns: 1fr;
    gap: 2rem;
  }

  .message-column {
    order: -1;
  }
}

@media (max-width: 768px) {
  .section {
    padding: 1.5rem;
  }

  .ir-stats {
    grid-template-columns: 1fr;
  }

  .legend {
    flex-direction: column;
    gap: 0.75rem;
  }

  .properties-grid {
    grid-template-columns: 1fr;
  }

  .code-actions {
    flex-direction: column;
  }

  .history-item {
    flex-direction: column;
    gap: 0.5rem;
    align-items: flex-start;
  }

  .file-info {
    margin-right: 0;
  }
}
</style>
